### PR TITLE
Automation of Rosa Scaling Benchmark (#444): Part 1

### PR DESCRIPTION
**Pull request by andyuk1986**
Refers to #444

### CODE REVIEW

**Comment by andyuk1986** [comment]
I am archiving the results directory which contains already aggregated report. Also as a summary I am archiving the stats.json files (saw that in other workflow). Please let me know, if it is necessary and if I need to commit results or summary or both to git repo (also have seen in other workflow).

**Comment by ahus1** [comment]
@andyuk1986 - I did a first review, and had a successful build when I chose just some very small values. See https://github.com/ahus1/keycloak-benchmark/actions/runs/5795138289/job/15706106755

I was wondering if I could remove the `deployMonitoring`, as the metrics would be recorded by Prometheus anyway. Let me know your thoughts.  

I'm now doing another full run to see the result.

Some notes about the changes I did: 
* Actions don't have types, and their defaults are always strings
* Create and delete work without start and stop
* I made the measurement period a parameter, to have faster smoke tests after script changes
* users per realm now matches the number of created entities

**Comment by andyuk1986** [comment]
@ahus1 - thanks a lot for the review. Very nice solution for ansible environment file, thanks for adding it. And yes, the deployMonitoring flag can be removed as prometheus records metrics anyway. I will remove that and I can squash commits to one.

**Comment by andyuk1986** [comment]
I have removed the `deployMonitoring` implementation part. May I squash the commits?

**Comment by ahus1** [comment]
@andyuk1986 - yes, merging would have been ok, but I also have the button on the GitHub UI to squash them during the merge - and this is what I did.

Thank you for your contribution!

**Pull request merged**
