### PR TITLE
Using an array when generating the CLI options for the downstream script

### LINKED ISSUE #204: kcb.sh doesn't pass on the quotes to the Java CLI, fails with the new scope flag to parse --scope="openid profile offline_token"
### Describe the bug

kcb.sh doesn't pass on the quotes to the Java CLI, fails with the new scope flag to parse --scope="openid profile offline_token"

### Version

nightly (9/16/2022)

### Expected behavior

kcb.sh should parse the multi subject word of scope successfully and pass it to the Java CLI.

### Actual behavior

kcb.sh doesn't pass on the quotes to the Java CLI, fails with the new scope flag to parse --scope="openid profile offline_token"

```
$ ./kcb.sh   --scenario=keycloak.scenario.authentication.AuthorizationCode --server-url={KEYCLOAK_SERVER_URL}   --realm-name=test-realm --scope="openid profile offline_token"
Error: Could not find or load main class profile
Caused by: java.lang.ClassNotFoundException: profile

```

with the debug flag, running against a minikube setup:

```
+ case "`uname`" in
++ uname
++ readlink -f ./kcb.sh
+ RESOLVED_NAME=/home/kakella/code/keycloak-benchmark/benchmark/target/keycloak-benchmark-0.8-SNAPSHOT/bin/kcb.sh
+ '[' x/home/kakella/code/keycloak-benchmark/benchmark/target/keycloak-benchmark-0.8-SNAPSHOT/bin/kcb.sh = x ']'
+ GREP=grep
++ dirname /home/kakella/code/keycloak-benchmark/benchmark/target/keycloak-benchmark-0.8-SNAPSHOT/bin/kcb.sh
+ DIRNAME=/home/kakella/code/keycloak-benchmark/benchmark/target/keycloak-benchmark-0.8-SNAPSHOT/bin
+ JAVA_OPTS=-server
+ JAVA_OPTS='-server -Xmx1G -XX:+HeapDumpOnOutOfMemoryError'
+ DEBUG_MODE=false
+ DEBUG_PORT=8787
+ CONFIG_ARGS=
+ SCENARIO=keycloak.scenario.authentication.ClientSecret
+ '[' 4 -gt 0 ']'
+ case "$1" in
+ SCENARIO=keycloak.scenario.authentication.AuthorizationCode
+ shift
+ '[' 3 -gt 0 ']'
+ case "$1" in
+ [[ --server-url=http://keycloak.192.168.39.218.nip.io = --* ]]
+ CONFIG_ARGS=' -Dserver-url=http://keycloak.192.168.39.218.nip.io'
+ shift
+ '[' 2 -gt 0 ']'
+ case "$1" in
+ [[ --realm-name=test-realm = --* ]]
+ CONFIG_ARGS=' -Dserver-url=http://keycloak.192.168.39.218.nip.io -Drealm-name=test-realm'
+ shift
+ '[' 1 -gt 0 ']'
+ case "$1" in
+ [[ --scope=openid profile offline_token = --* ]]
+ CONFIG_ARGS=' -Dserver-url=http://keycloak.192.168.39.218.nip.io -Drealm-name=test-realm -Dscope=openid profile offline_token'
+ shift
+ '[' 0 -gt 0 ']'
+ '[' false = true ']'
+ CLASSPATH_OPTS='/home/kakella/code/keycloak-benchmark/benchmark/target/keycloak-benchmark-0.8-SNAPSHOT/bin/../lib/*'
+ exec java -server -Xmx1G -XX:+HeapDumpOnOutOfMemoryError -Dserver-url=http://keycloak.192.168.39.218.nip.io -Drealm-name=test-realm -Dscope=openid profile offline_token -cp /home/kakella/code/keycloak-benchmark/benchmark/target/keycloak-benchmark-0.8-SNAPSHOT/bin/../lib/keycloak-benchmark-0.8-SNAPSHOT.jar io.gatling.app.Gatling -bf /home/kakella/code/keycloak-benchmark/benchmark/target/keycloak-benchmark-0.8-SNAPSHOT/bin -rf /home/kakella/code/keycloak-benchmark/benchmark/target/keycloak-benchmark-0.8-SNAPSHOT/bin/../results -s keycloak.scenario.authentication.AuthorizationCode
Error: Could not find or load main class profile
Caused by: java.lang.ClassNotFoundException: profile


```

### How to Reproduce?

run against an existing Keycloak server with the below command

```
./kcb.sh   --scenario=keycloak.scenario.authentication.AuthorizationCode --server-url={KEYCLOAK_SERVER_URL}   --realm-name=test-realm --scope="openid profile offline_token"
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by ahus1**
This avoids blanks in parameters to split them.

Closes #204

### CODE REVIEW

**Comment by ahus1** [comment]
Hi @kami619 - this fixes the issue where blanks split parameters on the CLI. 

With tracing enabled, this now calls: 

> exec java -server -Xmx1G -XX:+HeapDumpOnOutOfMemoryError '-Dserver-url={KEYCLOAK_SERVER_URL}' -Drealm-name=test-realm '-Dscope=openid profile offline_token' ...

(see the quotes it adds).

I'd be happy if you could give it a review. Thanks!

**Comment by kami619** [comment]
adding a reference to an internal project, where we had an instance of this happening to consuem CONFIG_ARGS, but I believe this should not be a blocker for this issue. We can look into it, when we have a need for such use cases - https://github.com/tkyjovsk/ciam-985/blob/f437310539fbceeb12b7bcb95191d0d7de3b2d11/keycloak-benchmark/roles/keycloak_benchmark/tasks/run.yml#L14

**Comment by kami619** [comment]
its works as expected, however in the existing minikube based setup, if run the below command, i get a bad redirect, its probably due to the config and how its done. I am accepting this PR for now, I will work with you on whats causing the redirect issue.

```
./kcb.sh --scenario=keycloak.scenario.authentication.AuthorizationCode --server-url=https://keycloak.192.168.39.131.nip.io/ --realm-name=test-realm --scope="openid profile offline_token"
18:02:56.218 [INFO ] a.e.s.Slf4jLogger - Slf4jLogger started
==========================================================
Target servers: [https://keycloak.192.168.39.131.nip.io/]
Scenario:
 Name: keycloak.scenario.authentication.AuthorizationCode
Population:
  realms: 1
  users-per-realm: 1
  clients-per-realm: 1
  realm-name: test-realm
  username: Not defined
  user-password: Not defined
Runtime:
  users-per-sec: 1.0 (Open Workload Model)
  ramp-up: 5
  warm-up: 0
  measurement: 30
  user-think-time: 0
  refresh-token-period: 0
Service Level Agreements:
  Max Error Percentage: 0.0
  Max Mean Response Time: 300
Timestamps: 
  Start: 18:02:56
  Warm-Up Start: 18:03:01
  Measurement Start: 18:03:01
  Measurement End: 18:03:31
==========================================================
Simulation keycloak.scenario.authentication.AuthorizationCode started...

================================================================================
2022-10-03 18:03:03                                           5s elapsed
---- Requests ------------------------------------------------------------------
> Global                                                   (OK=0      KO=2     )
> Browser to Log In Endpoint                               (OK=0      KO=2     )
---- Errors --------------------------------------------------------------------
> status.find.is(200), but actually found 302                         2 (100.0%)

---- Authentication - Authorization Code Username/Password ---------------------
[####                                                                      ]  6%
          waiting: 30     / active: 0      / done: 2     
================================================================================


```

**Review by kami619 — APPROVED** [review]

**Comment by ahus1** [comment]
@kami619 - thanks for testing this. I found a bug in the docs, it should have been "offline_access" as a scope instead of "offline_token". 

I fixed this in the docs (see 8af7cfe895d7c1b4e45b711e3b0ec9a8b92230b7); the following now worked for me: 

> bin/kcb.sh --scenario=keycloak.scenario.authentication.AuthorizationCode --server-url=https://keycloak.192.168.39.153.nip.io/ --realm-name=test-realm --scope="openid profile offline_access"

```
================================================================================
2022-10-06 10:24:29                                           5s elapsed
---- Requests ------------------------------------------------------------------
> Global                                                   (OK=6      KO=0     )
> Browser to Log In Endpoint                               (OK=2      KO=0     )
> Browser posts correct credentials                        (OK=2      KO=0     )
> Exchange Code                                            (OK=2      KO=0     )

---- Authentication - Authorization Code Username/Password ---------------------
[####                                                                      ]  6%
          waiting: 30     / active: 0      / done: 2     
================================================================================
```

I also double checked that the offline sessions appear in the database when map storage is enabled. It seems that two sessions are created; one online and one offline session; this is probably intended.

**Comment by kami619** [comment]
great thanks for tracking this issue to closure. I think fully unblocks us from running the offline session flow in general. @ahus1

**Pull request merged**
