### PR TITLE
basic python script to generate PDFs of the dashboards

### LINKED ISSUE #543: automate the grafana dashboard snapshots after the load test is completed
### Description

automate the grafana dashboard snapshots after the load test is completed

### Discussion

_No response_

### Motivation

It currently takes quite a few clicks for us to either take the PDF snapshots or the Grafana snapshots of the dashboards post a load test run. this ticket is a request to automate this process.

### Details

_No response_

### PR DESCRIPTION
**Pull request by kami619**
fixes #543 

- [x] create the pdf generation script from a grafana dashboard.
- [x] add the module to create auth keys on demand and delete them after report generation.
- [x] create a requirements file.
- [x] update docs and explain how to use this script.
- [x] connect the report generation tool with kcb.sh script, output the time_window parameter as part of the kcb.sh run asset.

### CODE REVIEW

**Comment by kami619** [comment]
Example usage:

```
$ python3 grafanaPdf.py --grafana_domain grafana.apps.gh-keycloak.XXXX.openshiftapps.com --admin_password XXXXXX --time_window "from=1694801561166&to=1694802033424" --keycloak_namespace "kamesh-keycloak"
CREATE GRAFANA API KEY
Navigated to the page, taking PDF now and saving it to ./grafana_report_keycloak-perf-tests_20230915_14:54:26.pdf
Navigated to the page, taking PDF now and saving it to ./grafana_report_keycloak-infinispan-board_20230915_14:54:26.pdf
Navigated to the page, taking PDF now and saving it to ./grafana_report_authentication-code-slo_20230915_14:54:26.pdf
Navigated to the page, taking PDF now and saving it to ./grafana_report_client-credentials-slo_20230915_14:54:26.pdf
DELETE GRAFANA API KEY
{'message': 'API key deleted'}

```

generated report pdfs:
[grafana_report_authentication-code-slo_20230915_14:54:26.pdf](https://github.com/keycloak/keycloak-benchmark/files/12623003/grafana_report_authentication-code-slo_20230915_14.54.26.pdf)

[grafana_report_client-credentials-slo_20230915_14:54:26.pdf](https://github.com/keycloak/keycloak-benchmark/files/12623004/grafana_report_client-credentials-slo_20230915_14.54.26.pdf)

[grafana_report_keycloak-infinispan-board_20230915_14:54:26.pdf](https://github.com/keycloak/keycloak-benchmark/files/12623005/grafana_report_keycloak-infinispan-board_20230915_14.54.26.pdf)

[grafana_report_keycloak-perf-tests_20230915_14:54:26.pdf](https://github.com/keycloak/keycloak-benchmark/files/12623006/grafana_report_keycloak-perf-tests_20230915_14.54.26.pdf)

**Review by pruivo — APPROVED** [review]
Works like a charm. Would it be possible to download `result_grafana_inputs.json` when we run with Ansible so I don't have to compute the timestamps by hand? :)

**Comment by kami619** [comment]
> Works like a charm. Would it be possible to download `result_grafana_inputs.json` when we run with Ansible so I don't have to compute the timestamps by hand? :)

thank you for reviewing and taking the time to try it Pedro. thats a good point you make., I think I can do it for Ansible flow as well, let me see if I can do this as part of this PR. @pruivo if not will create a separate ticket.

**Comment by kami619** [comment]
@pruivo I have updated the `ansible/benchmark.sh` to print a `from=xxxxxx&toxxxxxx` to the console to make it quick. I will think of a long term solution in the mean time as a separate ticket. hope that satisfies the immediate need. lmk if it looks good and I shall merge it in.

**Review by pruivo — APPROVED** [review]

**Pull request merged**
