### PR TITLE
Updating the dataprovider for KC19 and map storage

### LINKED ISSUE #179: Dataset module fails when it executes against the Map storage on Keycloak Quarkus based distribution
### Describe the bug

Dataset module fails when it executes against the Map storage on Keycloak quarkus based distro

### Version

nightly (8/30/2022)

### Expected behavior

Dataset module based spi's should have forward compatibility with the new storage layer, which would allow us to add data in a bulk way to test the benchmarks at a higher scale of data volume.

### Actual behavior

Dataset module fails with the below exception when run against any Map storage (JPA, CHM etc.,) on the Keycloak Quarkus based distribution

<details>
<summary>stacktrace</summary>

```
{
  "log": {
    "timestamp": "2022-08-29T20:04:53.167Z",
    "sequence": 5151,
    "loggerClassName": "org.jboss.logging.Logger",
    "loggerName": "org.keycloak.services.error.KeycloakErrorHandler",
    "level": "ERROR",
    "message": "Uncaught server error",
    "threadName": "executor-thread-4",
    "threadId": 31,
    "mdc": {},
    "ndc": "",
    "hostName": "keycloak-0",
    "processName": "QuarkusEntryPoint",
    "processId": 1,
    "exception": {
      "refId": 1,
      "exceptionType": "java.lang.NullPointerException",
      "message": null,
      "frames": [
        {
          "class": "org.keycloak.benchmark.dataset.TaskManager",
          "method": "u003cinitu003e",
          "line": 46
        },
        {
          "class": "org.keycloak.benchmark.dataset.DatasetResourceProvider",
          "method": "createRealms",
          "line": 126
        },
        {
          "class": "jdk.internal.reflect.NativeMethodAccessorImpl",
          "method": "invoke0"
        },
        {
          "class": "jdk.internal.reflect.NativeMethodAccessorImpl",
          "method": "invoke",
          "line": 62
        },
        {
          "class": "jdk.internal.reflect.DelegatingMethodAccessorImpl",
          "method": "invoke",
          "line": 43
        },
        {
          "class": "java.lang.reflect.Method",
          "method": "invoke",
          "line": 566
        },
        {
          "class": "org.jboss.resteasy.core.MethodInjectorImpl",
          "method": "invoke",
          "line": 170
        },
        {
          "class": "org.jboss.resteasy.core.MethodInjectorImpl",
          "method": "invoke",
          "line": 130
        },
        {
          "class": "org.jboss.resteasy.core.ResourceMethodInvoker",
          "method": "internalInvokeOnTarget",
          "line": 660
        },
        {
          "class": "org.jboss.resteasy.core.ResourceMethodInvoker",
          "method": "invokeOnTargetAfterFilter",
          "line": 524
        },
        {
          "class": "org.jboss.resteasy.core.ResourceMethodInvoker",
          "method": "lambda$invokeOnTarget$2",
          "line": 474
        },
        {
          "class": "org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext",
          "method": "filter",
          "line": 364
        },
        {
          "class": "org.jboss.resteasy.core.ResourceMethodInvoker",
          "method": "invokeOnTarget",
          "line": 476
        },
        {
          "class": "org.jboss.resteasy.core.ResourceMethodInvoker",
          "method": "invoke",
          "line": 434
        },
        {
          "class": "org.jboss.resteasy.core.ResourceLocatorInvoker",
          "method": "invokeOnTargetObject",
          "line": 192
        },
        {
          "class": "org.jboss.resteasy.core.ResourceLocatorInvoker",
          "method": "invoke",
          "line": 141
        },
        {
          "class": "org.jboss.resteasy.core.ResourceLocatorInvoker",
          "method": "invoke",
          "line": 32
        },
        {
          "class": "org.jboss.resteasy.core.SynchronousDispatcher",
          "method": "invoke",
          "line": 492
        },
        {
          "class": "org.jboss.resteasy.core.SynchronousDispatcher",
          "method": "lambda$invoke$4",
          "line": 261
        },
        {
          "class": "org.jboss.resteasy.core.SynchronousDispatcher",
          "method": "lambda$preprocess$0",
          "line": 161
        },
        {
          "class": "org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext",
          "method": "filter",
          "line": 364
        },
        {
          "class": "org.jboss.resteasy.core.SynchronousDispatcher",
          "method": "preprocess",
          "line": 164
        },
        {
          "class": "org.jboss.resteasy.core.SynchronousDispatcher",
          "method": "invoke",
          "line": 247
        },
        {
          "class": "io.quarkus.resteasy.runtime.standalone.RequestDispatcher",
          "method": "service",
          "line": 73
        },
        {
          "class": "io.quarkus.resteasy.runtime.standalone.VertxRequestHandler",
          "method": "dispatch",
          "line": 151
        },
        {
          "class": "io.quarkus.resteasy.runtime.standalone.VertxRequestHandler",
          "method": "handle",
          "line": 82
        },
        {
          "class": "io.quarkus.resteasy.runtime.standalone.VertxRequestHandler",
          "method": "handle",
          "line": 42
        },
        {
          "class": "io.vertx.ext.web.impl.RouteState",
          "method": "handleContext",
          "line": 1212
        },
        {
          "class": "io.vertx.ext.web.impl.RoutingContextImplBase",
          "method": "iterateNext",
          "line": 163
        },
        {
          "class": "io.vertx.ext.web.impl.RoutingContextImpl",
          "method": "next",
          "line": 141
        },
        {
          "class": "io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2",
          "method": "handle",
          "line": 67
        },
        {
          "class": "io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2",
          "method": "handle",
          "line": 55
        },
        {
          "class": "io.vertx.ext.web.impl.RouteState",
          "method": "handleContext",
          "line": 1212
        },
        {
          "class": "io.vertx.ext.web.impl.RoutingContextImplBase",
          "method": "iterateNext",
          "line": 163
        },
        {
          "class": "io.vertx.ext.web.impl.RoutingContextImpl",
          "method": "next",
          "line": 141
        },
        {
          "class": "io.quarkus.vertx.http.runtime.VertxHttpRecorder$5",
          "method": "handle",
          "line": 380
        },
        {
          "class": "io.quarkus.vertx.http.runtime.VertxHttpRecorder$5",
          "method": "handle",
          "line": 358
        },
        {
          "class": "io.vertx.ext.web.impl.RouteState",
          "method": "handleContext",
          "line": 1212
        },
        {
          "class": "io.vertx.ext.web.impl.RoutingContextImplBase",
          "method": "iterateNext",
          "line": 163
        },
        {
          "class": "io.vertx.ext.web.impl.RoutingContextImpl",
          "method": "next",
          "line": 141
        },
        {
          "class": "org.keycloak.quarkus.runtime.integration.web.QuarkusRequestFilter",
          "method": "lambda$createBlockingHandler$1",
          "line": 90
        },
        {
          "class": "io.vertx.core.impl.ContextImpl",
          "method": "lambda$null$0",
          "line": 159
        },
        {
          "class": "io.vertx.core.impl.AbstractContext",
          "method": "dispatch",
          "line": 100
        },
        {
          "class": "io.vertx.core.impl.ContextImpl",
          "method": "lambda$executeBlocking$1",
          "line": 157
        },
        {
          "class": "io.quarkus.vertx.core.runtime.VertxCoreRecorder$13",
          "method": "runWith",
          "line": 545
        },
        {
          "class": "org.jboss.threads.EnhancedQueueExecutor$Task",
          "method": "run",
          "line": 2449
        },
        {
          "class": "org.jboss.threads.EnhancedQueueExecutor$ThreadBody",
          "method": "run",
          "line": 1478
        },
        {
          "class": "org.jboss.threads.DelegatingRunnable",
          "method": "run",
          "line": 29
        },
        {
          "class": "org.jboss.threads.ThreadLocalResettingRunnable",
          "method": "run",
          "line": 29
        },
        {
          "class": "io.netty.util.concurrent.FastThreadLocalRunnable",
          "method": "run",
          "line": 30
        },
        {
          "class": "java.lang.Thread",
          "method": "run",
          "line": 829
        }
      ]
    }
  },
  "stream": "stdout",
  "time": "2022-08-29T20:04:53.171254649Z"
}
```
</details>

### How to Reproduce?

Using the provision/minikube module, 
- spin up the minikube based Keycloak setup with KC_STORAGE=jpa. 
- Now against that setup, execute the below curl command.
- Observe the Keycloak server logs for the NPE server side error when consuming this spi provider

```
https://keycloak.$(minikube ip).nip.io/realms/master/dataset/create-realms?count=1
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by ahus1**
Besides upgrading the dataprovider, it also 
* Refactors the documentation of the dataset provider to make use of the Antora features.
* Adds Keycloak remote debugging for the minikube setup.
* Adds a new endpoint `dataset/status-completed` to retrieve the latest completed task.
* Add support for problematic situations in the taskfile

Closes #179

### CODE REVIEW

**Comment by ahus1** [comment]
@kami619 - this is now ready to review. 

I tested this with the legacy store and the the JPA map store with PostgreSQL: 
* creation of a realm using the `dataset-import.sh` 
* looking at the `status` and the `status-completed` URLs

**Comment by kami619** [comment]
@ahus1 The changes seems to be working without issue on Legacy JPA and Map JPA stores, however, I have observed an exception with the cockroach DB + Map JPA store combination, with the below NPEs

```
{"timestamp":"2022-09-06T22:38:49.068Z","sequence":5026,"loggerClassName":"org.jboss.logging.Logger","loggerName":"org.keycloak.services.error.KeycloakErrorHandler","level":"ERROR","message":"Uncaught server error","threadName":"executor-thread-2","threadId":29,"mdc":{},"ndc":"","hostName":"keycloak-0","processName":"QuarkusEntryPoint","processId":1,"exception":{"refId":1,"exceptionType":"java.lang.NullPointerException","message":null,"frames":[{"class":"org.keycloak.benchmark.dataset.TaskManager","method":"<init>","line":46},{"class":"org.keycloak.benchmark.dataset.DatasetResourceProvider","method":"getStatus","line":730},{"class":"jdk.internal.reflect.NativeMethodAccessorImpl","method":"invoke0"},{"class":"jdk.internal.reflect.NativeMethodAccessorImpl","method":"invoke","line":62},{"class":"jdk.internal.reflect.DelegatingMethodAccessorImpl","method":"invoke","line":43},{"class":"java.lang.reflect.Method","method":"invoke","line":566},{"class":"org.jboss.resteasy.core.MethodInjectorImpl","method":"invoke","line":170},{"class":"org.jboss.resteasy.core.MethodInjectorImpl","method":"invoke","line":130},{"class":"org.jboss.resteasy.core.ResourceMethodInvoker","method":"internalInvokeOnTarget","line":660},{"class":"org.jboss.resteasy.core.ResourceMethodInvoker","method":"invokeOnTargetAfterFilter","line":524},{"class":"org.jboss.resteasy.core.ResourceMethodInvoker","method":"lambda$invokeOnTarget$2","line":474},{"class":"org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext","method":"filter","line":364},{"class":"org.jboss.resteasy.core.ResourceMethodInvoker","method":"invokeOnTarget","line":476},{"class":"org.jboss.resteasy.core.ResourceMethodInvoker","method":"invoke","line":434},{"class":"org.jboss.resteasy.core.ResourceLocatorInvoker","method":"invokeOnTargetObject","line":192},{"class":"org.jboss.resteasy.core.ResourceLocatorInvoker","method":"invoke","line":141},{"class":"org.jboss.resteasy.core.ResourceLocatorInvoker","method":"invoke","line":32},{"class":"org.jboss.resteasy.core.SynchronousDispatcher","method":"invoke","line":492},{"class":"org.jboss.resteasy.core.SynchronousDispatcher","method":"lambda$invoke$4","line":261},{"class":"org.jboss.resteasy.core.SynchronousDispatcher","method":"lambda$preprocess$0","line":161},{"class":"org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext","method":"filter","line":364},{"class":"org.jboss.resteasy.core.SynchronousDispatcher","method":"preprocess","line":164},{"class":"org.jboss.resteasy.core.SynchronousDispatcher","method":"invoke","line":247},{"class":"io.quarkus.resteasy.runtime.standalone.RequestDispatcher","method":"service","line":73},{"class":"io.quarkus.resteasy.runtime.standalone.VertxRequestHandler","method":"dispatch","line":151},{"class":"io.quarkus.resteasy.runtime.standalone.VertxRequestHandler","method":"handle","line":82},{"class":"io.quarkus.resteasy.runtime.standalone.VertxRequestHandler","method":"handle","line":42},{"class":"io.vertx.ext.web.impl.RouteState","method":"handleContext","line":1284},{"class":"io.vertx.ext.web.impl.RoutingContextImplBase","method":"iterateNext","line":173},{"class":"io.vertx.ext.web.impl.RoutingContextImpl","method":"next","line":140},{"class":"io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2","method":"handle","line":84},{"class":"io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2","method":"handle","line":71},{"class":"io.vertx.ext.web.impl.RouteState","method":"handleContext","line":1284},{"class":"io.vertx.ext.web.impl.RoutingContextImplBase","method":"iterateNext","line":173},{"class":"io.vertx.ext.web.impl.RoutingContextImpl","method":"next","line":140},{"class":"io.quarkus.vertx.http.runtime.VertxHttpRecorder$6","method":"handle","line":429},{"class":"io.quarkus.vertx.http.runtime.VertxHttpRecorder$6","method":"handle","line":407},{"class":"io.vertx.ext.web.impl.RouteState","method":"handleContext","line":1284},{"class":"io.vertx.ext.web.impl.RoutingContextImplBase","method":"iterateNext","line":173},{"class":"io.vertx.ext.web.impl.RoutingContextImpl","method":"next","line":140},{"class":"org.keycloak.quarkus.runtime.integration.web.QuarkusRequestFilter","method":"lambda$createBlockingHandler$1","line":90},{"class":"io.vertx.core.impl.ContextBase","method":"lambda$null$0","line":137},{"class":"io.vertx.core.impl.ContextInternal","method":"dispatch","line":264},{"class":"io.vertx.core.impl.ContextBase","method":"lambda$executeBlocking$1","line":135},{"class":"io.quarkus.vertx.core.runtime.VertxCoreRecorder$14","method":"runWith","line":557},{"class":"org.jboss.threads.EnhancedQueueExecutor$Task","method":"run","line":2449},{"class":"org.jboss.threads.EnhancedQueueExecutor$ThreadBody","method":"run","line":1478},{"class":"org.jboss.threads.DelegatingRunnable","method":"run","line":29},{"class":"org.jboss.threads.ThreadLocalResettingRunnable","method":"run","line":29},{"class":"io.netty.util.concurrent.FastThreadLocalRunnable","method":"run","line":30},{"class":"java.lang.Thread","method":"run","line":829}]}}
{"timestamp":"2022-09-06T22:38:49.134Z","sequence":5027,"loggerClassName":"org.jboss.logging.Logger","loggerName":"org.keycloak.services.error.KeycloakErrorHandler","level":"ERROR","message":"Uncaught server error","threadName":"executor-thread-2","threadId":29,"mdc":{},"ndc":"","hostName":"keycloak-0","processName":"QuarkusEntryPoint","processId":1,"exception":{"refId":1,"exceptionType":"java.lang.NullPointerException","message":null,"frames":[{"class":"org.keycloak.benchmark.dataset.TaskManager","method":"<init>","line":46},{"class":"org.keycloak.benchmark.dataset.DatasetResourceProvider","method":"getStatus","line":730},{"class":"jdk.internal.reflect.NativeMethodAccessorImpl","method":"invoke0"},{"class":"jdk.internal.reflect.NativeMethodAccessorImpl","method":"invoke","line":62},{"class":"jdk.internal.reflect.DelegatingMethodAccessorImpl","method":"invoke","line":43},{"class":"java.lang.reflect.Method","method":"invoke","line":566},{"class":"org.jboss.resteasy.core.MethodInjectorImpl","method":"invoke","line":170},{"class":"org.jboss.resteasy.core.MethodInjectorImpl","method":"invoke","line":130},{"class":"org.jboss.resteasy.core.ResourceMethodInvoker","method":"internalInvokeOnTarget","line":660},{"class":"org.jboss.resteasy.core.ResourceMethodInvoker","method":"invokeOnTargetAfterFilter","line":524},{"class":"org.jboss.resteasy.core.ResourceMethodInvoker","method":"lambda$invokeOnTarget$2","line":474},{"class":"org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext","method":"filter","line":364},{"class":"org.jboss.resteasy.core.ResourceMethodInvoker","method":"invokeOnTarget","line":476},{"class":"org.jboss.resteasy.core.ResourceMethodInvoker","method":"invoke","line":434},{"class":"org.jboss.resteasy.core.ResourceLocatorInvoker","method":"invokeOnTargetObject","line":192},{"class":"org.jboss.resteasy.core.ResourceLocatorInvoker","method":"invoke","line":141},{"class":"org.jboss.resteasy.core.ResourceLocatorInvoker","method":"invoke","line":32},{"class":"org.jboss.resteasy.core.SynchronousDispatcher","method":"invoke","line":492},{"class":"org.jboss.resteasy.core.SynchronousDispatcher","method":"lambda$invoke$4","line":261},{"class":"org.jboss.resteasy.core.SynchronousDispatcher","method":"lambda$preprocess$0","line":161},{"class":"org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext","method":"filter","line":364},{"class":"org.jboss.resteasy.core.SynchronousDispatcher","method":"preprocess","line":164},{"class":"org.jboss.resteasy.core.SynchronousDispatcher","method":"invoke","line":247},{"class":"io.quarkus.resteasy.runtime.standalone.RequestDispatcher","method":"service","line":73},{"class":"io.quarkus.resteasy.runtime.standalone.VertxRequestHandler","method":"dispatch","line":151},{"class":"io.quarkus.resteasy.runtime.standalone.VertxRequestHandler","method":"handle","line":82},{"class":"io.quarkus.resteasy.runtime.standalone.VertxRequestHandler","method":"handle","line":42},{"class":"io.vertx.ext.web.impl.RouteState","method":"handleContext","line":1284},{"class":"io.vertx.ext.web.impl.RoutingContextImplBase","method":"iterateNext","line":173},{"class":"io.vertx.ext.web.impl.RoutingContextImpl","method":"next","line":140},{"class":"io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2","method":"handle","line":84},{"class":"io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2","method":"handle","line":71},{"class":"io.vertx.ext.web.impl.RouteState","method":"handleContext","line":1284},{"class":"io.vertx.ext.web.impl.RoutingContextImplBase","method":"iterateNext","line":173},{"class":"io.vertx.ext.web.impl.RoutingContextImpl","method":"next","line":140},{"class":"io.quarkus.vertx.http.runtime.VertxHttpRecorder$6","method":"handle","line":429},{"class":"io.quarkus.vertx.http.runtime.VertxHttpRecorder$6","method":"handle","line":407},{"class":"io.vertx.ext.web.impl.RouteState","method":"handleContext","line":1284},{"class":"io.vertx.ext.web.impl.RoutingContextImplBase","method":"iterateNext","line":173},{"class":"io.vertx.ext.web.impl.RoutingContextImpl","method":"next","line":140},{"class":"org.keycloak.quarkus.runtime.integration.web.QuarkusRequestFilter","method":"lambda$createBlockingHandler$1","line":90},{"class":"io.vertx.core.impl.ContextBase","method":"lambda$null$0","line":137},{"class":"io.vertx.core.impl.ContextInternal","method":"dispatch","line":264},{"class":"io.vertx.core.impl.ContextBase","method":"lambda$executeBlocking$1","line":135},{"class":"io.quarkus.vertx.core.runtime.VertxCoreRecorder$14","method":"runWith","line":557},{"class":"org.jboss.threads.EnhancedQueueExecutor$Task","method":"run","line":2449},{"class":"org.jboss.threads.EnhancedQueueExecutor$ThreadBody","method":"run","line":1478},{"class":"org.jboss.threads.DelegatingRunnable","method":"run","line":29},{"class":"org.jboss.threads.ThreadLocalResettingRunnable","method":"run","line":29},{"class":"io.netty.util.concurrent.FastThreadLocalRunnable","method":"run","line":30},{"class":"java.lang.Thread","method":"run","line":829}]}}
{"timestamp":"2022-09-06T22:38:49.199Z","sequence":5028,"loggerClassName":"org.jboss.logging.Logger","loggerName":"org.keycloak.services.error.KeycloakErrorHandler","level":"ERROR","message":"Uncaught server error","threadName":"executor-thread-2","threadId":29,"mdc":{},"ndc":"","hostName":"keycloak-0","processName":"QuarkusEntryPoint","processId":1,"exception":{"refId":1,"exceptionType":"java.lang.NullPointerException","message":null,"frames":[{"class":"org.keycloak.benchmark.dataset.TaskManager","method":"<init>","line":46},{"class":"org.keycloak.benchmark.dataset.DatasetResourceProvider","method":"getStatus","line":730},{"class":"jdk.internal.reflect.NativeMethodAccessorImpl","method":"invoke0"},{"class":"jdk.internal.reflect.NativeMethodAccessorImpl","method":"invoke","line":62},{"class":"jdk.internal.reflect.DelegatingMethodAccessorImpl","method":"invoke","line":43},{"class":"java.lang.reflect.Method","method":"invoke","line":566},{"class":"org.jboss.resteasy.core.MethodInjectorImpl","method":"invoke","line":170},{"class":"org.jboss.resteasy.core.MethodInjectorImpl","method":"invoke","line":130},{"class":"org.jboss.resteasy.core.ResourceMethodInvoker","method":"internalInvokeOnTarget","line":660},{"class":"org.jboss.resteasy.core.ResourceMethodInvoker","method":"invokeOnTargetAfterFilter","line":524},{"class":"org.jboss.resteasy.core.ResourceMethodInvoker","method":"lambda$invokeOnTarget$2","line":474},{"class":"org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext","method":"filter","line":364},{"class":"org.jboss.resteasy.core.ResourceMethodInvoker","method":"invokeOnTarget","line":476},{"class":"org.jboss.resteasy.core.ResourceMethodInvoker","method":"invoke","line":434},{"class":"org.jboss.resteasy.core.ResourceLocatorInvoker","method":"invokeOnTargetObject","line":192},{"class":"org.jboss.resteasy.core.ResourceLocatorInvoker","method":"invoke","line":141},{"class":"org.jboss.resteasy.core.ResourceLocatorInvoker","method":"invoke","line":32},{"class":"org.jboss.resteasy.core.SynchronousDispatcher","method":"invoke","line":492},{"class":"org.jboss.resteasy.core.SynchronousDispatcher","method":"lambda$invoke$4","line":261},{"class":"org.jboss.resteasy.core.SynchronousDispatcher","method":"lambda$preprocess$0","line":161},{"class":"org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext","method":"filter","line":364},{"class":"org.jboss.resteasy.core.SynchronousDispatcher","method":"preprocess","line":164},{"class":"org.jboss.resteasy.core.SynchronousDispatcher","method":"invoke","line":247},{"class":"io.quarkus.resteasy.runtime.standalone.RequestDispatcher","method":"service","line":73},{"class":"io.quarkus.resteasy.runtime.standalone.VertxRequestHandler","method":"dispatch","line":151},{"class":"io.quarkus.resteasy.runtime.standalone.VertxRequestHandler","method":"handle","line":82},{"class":"io.quarkus.resteasy.runtime.standalone.VertxRequestHandler","method":"handle","line":42},{"class":"io.vertx.ext.web.impl.RouteState","method":"handleContext","line":1284},{"class":"io.vertx.ext.web.impl.RoutingContextImplBase","method":"iterateNext","line":173},{"class":"io.vertx.ext.web.impl.RoutingContextImpl","method":"next","line":140},{"class":"io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2","method":"handle","line":84},{"class":"io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2","method":"handle","line":71},{"class":"io.vertx.ext.web.impl.RouteState","method":"handleContext","line":1284},{"class":"io.vertx.ext.web.impl.RoutingContextImplBase","method":"iterateNext","line":173},{"class":"io.vertx.ext.web.impl.RoutingContextImpl","method":"next","line":140},{"class":"io.quarkus.vertx.http.runtime.VertxHttpRecorder$6","method":"handle","line":429},{"class":"io.quarkus.vertx.http.runtime.VertxHttpRecorder$6","method":"handle","line":407},{"class":"io.vertx.ext.web.impl.RouteState","method":"handleContext","line":1284},{"class":"io.vertx.ext.web.impl.RoutingContextImplBase","method":"iterateNext","line":173},{"class":"io.vertx.ext.web.impl.RoutingContextImpl","method":"next","line":140},{"class":"org.keycloak.quarkus.runtime.integration.web.QuarkusRequestFilter","method":"lambda$createBlockingHandler$1","line":90},{"class":"io.vertx.core.impl.ContextBase","method":"lambda$null$0","line":137},{"class":"io.vertx.core.impl.ContextInternal","method":"dispatch","line":264},{"class":"io.vertx.core.impl.ContextBase","method":"lambda$executeBlocking$1","line":135},{"class":"io.quarkus.vertx.core.runtime.VertxCoreRecorder$14","method":"runWith","line":557},{"class":"org.jboss.threads.EnhancedQueueExecutor$Task","method":"run","line":2449},{"class":"org.jboss.threads.EnhancedQueueExecutor$ThreadBody","method":"run","line":1478},{"class":"org.jboss.threads.DelegatingRunnable","method":"run","line":29},{"class":"org.jboss.threads.ThreadLocalResettingRunnable","method":"run","line":29},{"class":"io.netty.util.concurrent.FastThreadLocalRunnable","method":"run","line":30},{"class":"java.lang.Thread","method":"run","line":829}]}}
```

**Comment by kami619** [comment]
Found a different issue when trying to create the users using the below command 

```
$ ./dataset-import.sh -u '10 realm-3'
Creating 10 user/s in realm realm-3
{"status":"Task started successfully","task":{"startTimeMs":"1662738157595","message":"Creation of 10 users in the realm realm-3"},"task-status-url":"https://keycloak.192.168.39.49.nip.io/realms/master/dataset/status"}

```
[create-users-persistance-exception.txt](https://github.com/keycloak/keycloak-benchmark/files/9536980/create-users-persistance-exception.txt)


keycloak logs attached with the full sequence

**Comment by ahus1** [comment]
@kami619 - the problems you see might be special to CockroachDB as it tried to serialize alle accesses and might then fail. I'd like to have a new issue for that, and merge this PR if everything else works ok with PostgreSQL.

**Comment by kami619** [comment]
@ahus1 I was about to suggest that, this would be the Cockroach DB being different, I shall test it for other stores and log a new issue for Cockroach DB. Thanks again.

**Comment by kami619** [comment]
With the JPA and PostgreSQL DB `.env` vars in the minikube setup, trying to create the offline sessions fails with the below keycloak server side exception

command:
```
$ ./dataset-import.sh -o '100 realm-1'
Creating 100 offline sessions in realm realm-1
{"status":"Task started successfully","task":{"startTimeMs":"1662741686298","message":"Creation of 100 offline sessions"},"task-status-url":"https://keycloak.192.168.39.49.nip.io/realms/master/dataset/status"}
```

keycloak server logs:
```
{"timestamp":"2022-09-09T16:41:26.303Z","sequence":5083,"loggerClassName":"org.jboss.logging.Logger","loggerName":"org.keycloak.benchmark.dataset.DatasetResourceProvider","level":"INFO","message":"Trigger creating offline sessions with the configuration: DatasetConfig [ \n realm-prefix: realm-\n count: 100\n client-prefix: client-\n user-prefix: user-\n transaction-timeout: 300\n threads-count: 5\n task-timeout: 3600\n]","threadName":"executor-thread-13","threadId":48,"mdc":{},"ndc":"","hostName":"keycloak-0","processName":"QuarkusEntryPoint","processId":1}
{"timestamp":"2022-09-09T16:41:26.305Z","sequence":5084,"loggerClassName":"org.jboss.logging.Logger","loggerName":"org.keycloak.benchmark.dataset.DatasetResourceProvider","level":"INFO","message":"Will create offline sessions in the realms 'realm-0' - 'realm-1'","threadName":"executor-thread-13","threadId":48,"mdc":{},"ndc":"","hostName":"keycloak-0","processName":"QuarkusEntryPoint","processId":1}
{"timestamp":"2022-09-09T16:41:26.314Z","sequence":5085,"loggerClassName":"org.jboss.logging.Logger","loggerName":"org.keycloak.benchmark.dataset.ExecutorHelper","level":"INFO","message":"Waiting for tasks to complete","threadName":"Thread-8","threadId":65,"mdc":{},"ndc":"","hostName":"keycloak-0","processName":"QuarkusEntryPoint","processId":1}
{"timestamp":"2022-09-09T16:41:26.32Z","sequence":5086,"loggerClassName":"org.jboss.logging.Logger","loggerName":"org.keycloak.benchmark.dataset.DatasetResourceProvider","level":"ERROR","message":"unable to complete task","threadName":"Thread-8","threadId":65,"mdc":{},"ndc":"","hostName":"keycloak-0","processName":"QuarkusEntryPoint","processId":1,"exception":{"refId":1,"exceptionType":"java.util.concurrent.ExecutionException","message":"java.lang.IllegalStateException: Not found user with username 'user-0' in the realm 'realm-0'","frames":[{"class":"java.util.concurrent.FutureTask","method":"report","line":122},{"class":"java.util.concurrent.FutureTask","method":"get","line":191},{"class":"org.keycloak.benchmark.dataset.ExecutorHelper","method":"waitForAllToFinish","line":67},{"class":"org.keycloak.benchmark.dataset.DatasetResourceProvider","method":"createOfflineSessionsImpl","line":619},{"class":"org.keycloak.benchmark.dataset.DatasetResourceProvider","method":"lambda$createOfflineSessions$16","line":560},{"class":"java.lang.Thread","method":"run","line":829}],"causedBy":{"exception":{"refId":2,"exceptionType":"java.lang.IllegalStateException","message":"Not found user with username 'user-0' in the realm 'realm-0'","frames":[{"class":"org.keycloak.benchmark.dataset.DatasetResourceProvider","method":"lambda$createOfflineSessionsImpl$17","line":595},{"class":"org.keycloak.models.utils.KeycloakModelUtils","method":"runJobInTransaction","line":250},{"class":"org.keycloak.models.utils.KeycloakModelUtils","method":"runJobInTransactionWithTimeout","line":280},{"class":"org.keycloak.benchmark.dataset.ExecutorHelper","method":"lambda$addTaskRunningInTransaction$0","line":58},{"class":"java.util.concurrent.Executors$RunnableAdapter","method":"call","line":515},{"class":"java.util.concurrent.FutureTask","method":"run","line":264},{"class":"java.util.concurrent.ThreadPoolExecutor","method":"runWorker","line":1128},{"class":"java.util.concurrent.ThreadPoolExecutor$Worker","method":"run","line":628},{"class":"java.lang.Thread","method":"run","line":829}]}}}}
```

**Comment by ahus1** [comment]
@kami619 - I had a look and the call to create offline sessions doesn't support the realm parameter. 

It will works as follows: 
* with the configured "realm-prefix" (which can also be passed on via the URL), it finds the last created realm.
* it then creates the offline sessions across all realm starting with realm-0, assuming that all users exist across all the realms.

Please create an issue to fix the `dataset-import.sh` script and its documentation.

**Comment by kami619** [comment]
ah ok, thanks. I didn't look from that view, I will log a ticket to fix those.

**Pull request merged**
