### PR TITLE
Integrate with Kraken-Chaos

### PR DESCRIPTION
**Pull request by pruivo**
Added tasks to randomly kill pods (gossip router, infinispan or keycloak).

https://github.com/krkn-chaos/krkn-hub/tree/main

### CODE REVIEW

**Comment by pruivo** [comment]
I wasn't thinking about the SPIKE task at all. I was just sharing what I was using. I'm putting everything in the same taskfile to have just a single `.env` file with everything we need to reproduce it. If we split it to a different directory, we would have to keep the `.env` variables in sync between them (number of replicas, namespace...)
I can do whatever the team prefers :+1:

**Comment by pruivo** [comment]
I can move the tasks to a different file, `Chaos.yaml` and include it in the main `Taskfile.yaml`. The task name will be prefixed but it will keep the main taskfile smaller.

```
$ go-task --list
* chaos:chaos-kill-gossip-router:       Kills the JGroups Gossip Router pod
* chaos:chaos-kill-infinispan:          Kills a random Infinispan pod
* chaos:chaos-kill-keycloak:            Kills a random Keycloak pod
```

I could do the same for other tasks as well (benchmark, monitoring, route54, global-accelerator)

**Comment by kami619** [comment]
Sure thing, I think `Chaos.yaml` seems like a good idea. We could do the split up for `benchmark, monitoring, route53, glb` in a separate PR to be cleaner.

**Comment by pruivo** [comment]
Done! I've renamed the task's name to avoid repeating the word `chaos`. Current task list
```
$ go-task --list
task: Available tasks for this project:
* dataset-import-rosa-cluster:       Triggers the dataset creation task in the ROSA cluster route. It does not wait for completion.
* dataset-import-route53:            Triggers the dataset creation task using the Route53 load balancer. It does not wait for completion.
* default:                           Deploys Infinispan, Aurora DB and Keycloak in a Cross-Site deployment using ROSA clusters
* delete-aurora:                     Deletes Aurora Database
* ec2-create:                        Creates the EC2 workers
* ec2-delete:                        Deletes the EC2 workers
* ec2-run-rosa-cluster:              Runs a Gatling scenario in EC2 using ROSA cluster route
* ec2-run-route53:                   Runs a Gatling scenario in EC2 using Route53 load balancer
* global-accelerator-create:         Creates AWS Global Accelerator for active-active replication
* global-accelerator-delete:         Deletes AWS Global Accelerator for active-active replication
* grafana-snapshot:                  Takes a snapshot from the Grafana Dashboards into PDF files
* monitoring:                        Install grafana dashboards in both ROSA clusters
* route53:                           Creates Route53 primary/backup DNS records
* trigger-failover:                  Triggers the failover script
* undeploy:                          Undeploy Infinispan and Keycloak in a Cross-Site deployment using ROSA clusters
* chaos:kill-gossip-router:          Kills the JGroups Gossip Router pod
* chaos:kill-infinispan:             Kills a random Infinispan pod
* chaos:kill-keycloak:               Kills a random Keycloak pod
```

**Comment by kami619** [comment]
Thanks Pedro, I am merging this PR and will test it from main branch and add docs once I do that in a separate PR. Thanks for the quick changes and awesome addition to the framework.

**Review by kami619 — APPROVED** [review]

**Pull request merged**
