### PR TITLE
Remove sessions caches from KCB when Persistent Sessions is enabled

### LINKED ISSUE #953: Remove sessions caches from KCB when Persistent Sessions is enabled
For completeness, the caches `sessions`, `clientSessions`, `offlineSessions`, and `offlineClientSessions` should not be created in the external Infinispan cluster. Those are not used when the sessions are stored in the database.

### PR DESCRIPTION
**Pull request by pruivo**
Closes #953

### CODE REVIEW

**Comment by pruivo** [comment]
> Depends on [keycloak/keycloak#32416](https://github.com/keycloak/keycloak/issues/32416)

"depends" is a strong word, it will just print warnings about the caches not being found. Those are from the lb-check endpoint.

**Comment by ahus1** [comment]
> it will just print warnings about the caches not being found

Will the `lb-check fail` of they don't exist? Or should I rather wait for the PR to be merged first?

**Comment by pruivo** [comment]
When the cache does not exist, it skips the cache. The cache is always `UP`.

**Comment by pruivo** [comment]
Updated `build.sh` to generate the example for the Keycloak docs.

**Review by ahus1 — CHANGES_REQUESTED** [review]
Thank you for this PR!

I gave it a test run here: https://github.com/keycloak/keycloak-benchmark/actions/runs/10592774827/job/29353263858

Good news: The deployment worked, and I can log in to the environment.

Bad news: The functional tests fail as some remote caches are not available. 

Please have a look. Thanks!

```
java.lang.NullPointerException: Cannot invoke "org.infinispan.client.hotrod.RemoteCache.keySet()" because "this.cacheHotRodClient" is null
	at org.keycloak.benchmark.crossdc.client.ExternalInfinispanClient$ExternalCache.keys(ExternalInfinispanClient.java:135)
	at org.keycloak.benchmark.crossdc.AbstractCrossDCTest.lambda$setUpTestEnvironment$1(AbstractCrossDCTest.java:87)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:1024)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at org.keycloak.benchmark.crossdc.AbstractCrossDCTest.setUpTestEnvironment(AbstractCrossDCTest.java:86)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	Suppressed: jakarta.ws.rs.NotFoundException: HTTP 404 Not Found
		at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.handleErrorStatus(ClientInvocation.java:242)
		at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.extractResult(ClientInvocation.java:216)
		at org.jboss.resteasy.client.jaxrs.internal.proxy.extractors.BodyEntityExtractor.extractEntity(BodyEntityExtractor.java:59)
		at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invokeSync(ClientInvoker.java:136)
		at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invoke(ClientInvoker.java:103)
		at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientProxy.invoke(ClientProxy.java:102)
		at jdk.proxy2/jdk.proxy2.$Proxy53.toRepresentation(Unknown Source)
		at org.keycloak.benchmark.crossdc.AbstractCrossDCTest.tearDownTestEnvironment(AbstractCrossDCTest.java:160)
		... 3 more
```

**Comment by pruivo** [comment]
I've updated the Infinispan version and dealt with the nonexisting caches.

**Review by ahus1 — APPROVED** [review]
Functional tests are looking good, load test started and continue to run and look good. 
Approving. Thanks!

https://github.com/keycloak/keycloak-benchmark/actions/runs/10595248616/job/29361306746

**Pull request merged**
