### PR TITLE
add new perfInsights.py script to analyse the data generated in result_data branch

### PR DESCRIPTION
**Pull request by kami619**
We are adding a script to analyze the generated performance test run results efficiently.

usage:

python perfInsights.py <directory_on_result_data_github_branch> <outputDir>

```
python perfInsights.py rosa_scalability/2024/07/23 results
```

Sample Output: https://github.com/user-attachments/files/16390815/rosa_scalability_runs_comparision.zip

### CODE REVIEW

**Comment by kami619** [comment]
@ahus1 if you like the script, I shall add docs for it and commit to this PR, lmk.

**Comment by ahus1** [comment]
I suppose this is some overlap with what we can do with Horreum, still it might be good for ad-hoc or explorative analysis. Feel free to add it to our repo together with some docs.

**Comment by kami619** [comment]
@ahus1 good to review and merge when you have some capacity to look at it. I have added the docs.

**Review by ahus1 — APPROVED** [review]
Thank you for this script and the docs!

**Pull request merged**
