### PR TITLE
Reverting to an old setup where keep all sessions in memory on the Infinispan side of things

### LINKED ISSUE #934: Revert change to have only 10_000 entries in Infinispan caches
### Describe the bug

We always allows only 10_000 entries in remote Infinispan for sessions. This was done when we first introduced persistent sessions. This is now obsolete, as with persistent sessions we don't use the external caches, and it is wrong when we use them for the external Infinispan only setups.

### Version

main

### Expected behavior

All valid entries should be kept in the cache.

### Actual behavior

10_000 entries max in the external cache.

### How to Reproduce?

Look at the nightly run.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by ahus1**
Closes #934

### CODE REVIEW

**Comment by kami619** [comment]
@ahus1 do we also need to update the following locations? 

https://github.com/keycloak/keycloak-benchmark/blob/a1a40e761604c493e7deada0726780ea0a77dd17/provision/minikube/keycloak/config/kcb-infinispan-cache-config.xml#L31

https://github.com/keycloak/keycloak-benchmark/blob/a1a40e761604c493e7deada0726780ea0a77dd17/provision/minikube/keycloak/config/kcb-infinispan-cache-remote-store-config.xml#L32

**Comment by ahus1** [comment]
@kami619 - no, those locations are local embedded caches where we we cache entries which we retrieved from the database earlier. Those are expected to be limited. Everything that is evicted there is later re-loaded from the database when needed.

**Comment by kami619** [comment]
thanks @ahus1.

**Review by kami619 — APPROVED** [review]
lgtm

**Pull request merged**
