### PR TITLE
Update to ARM worker node types

### LINKED ISSUE #1022: Support ARM based Keycloak deployments on ROSA
### Description

- Identify remaining services on Keycloak Benchmark that don't support ARM, possibly leading to a mixed ARM and non-ARM cluster

### Discussion

_No response_

### Motivation

_No response_

### Details

_No response_

### PR DESCRIPTION
**Pull request by kami619**
Fixes #1022

### CODE REVIEW

**Comment by ahus1** [comment]
Thank you - I think it will be green when you roll back the changes in `provision/minikube/keycloak/templates/keycloak.yaml`, the build will be green. Still, we might want those changes to be able to test in a mixed cluster, so then they would need to be conditional on an architecture selector.

**Comment by mhajas** [comment]
We can use this in `keycloak.yaml`
```
{{ if eq .Values.environment "openshift" }}
```

**Comment by ahus1** [comment]
Hm, with the change `{{ if eq .Values.environment "openshift" }}` we now enforce ARM on OpenShift all the time. We would need to do this only on mixed clusters, as arm would be the default anyway in a pure ARM cluster. I'll comment in the parent issue about what is in scope and what not.

**Review by mhajas — APPROVED** [review]
I am merging this so we have the results on Monday

**Pull request merged**
