### PR TITLE
Dataset script - documentation/create-realms (refactoring #177)

### PR DESCRIPTION
**Pull request by lhanusov**
This PR is built on top of the previous PR: https://github.com/keycloak/keycloak-benchmark/pull/177 and it refactors the case command, documentation and mainly the create-realms function.

### CODE REVIEW

**Comment by kami619** [comment]
@lhanusov Thanks for the PR, I think it would be great to add more context about the problem we are trying to address. 

Preferably, its always good to have an Issue created in the GH Issues section, laying out the problem and potential solution path(s), paving way for a design discussion. Also, you can provide a solution in the form of a PR, trying to address the GH Issue.

A good PR to follow would be this one, where I made similar mistakes - https://github.com/keycloak/keycloak-benchmark/pull/59

There is a task on the maintainers to add this information to the contribution guidelines of this project to make it more explicit. But until that point, please try to follow these. Thanks.

**Review by kami619 — CHANGES_REQUESTED** [review]
please make changes to the PR based on the guidelines provided in the earlier comment and re-submit for review.

**Comment by lhanusov** [comment]
@kami619 Hi Kamesh, it makes sense -> updated. Thanks

**Comment by kami619** [comment]
lgtm

**Pull request merged**
