### PR TITLE
Pin the versions of the different helm charts and fix the loki values

### LINKED ISSUE #189: minikube provisioning : loki logs are not showing up in the grafana explorer
### Describe the bug

loki logs are not showing up in the grafana explorer within the minikube setup of the keycloak application under the provision/minikube module

image

### Version

https://github.com/keycloak/keycloak-benchmark/commit/fdc7fe7a499eb4a6a1b539be2f0c99ec50a0624c

### Expected behavior

loki logs should be loading without issue when the monitoring variable is set to true in the Keycloak minikube env.

### Actual behavior

loki logs doesn't show up from the grafana Explore view

### How to Reproduce?

provision the minikube based keycloak with the main branch and once the setup comes up fully, observe the loki logs under the grafana app

### Anything else?

The request thats failing on the grafana GUI is :

```
https://grafana.192.168.39.9.nip.io/api/datasources/3/resources/labels?start=1662477253975000000&end=1662480853975000000
```

Seeing 401's in the loki container logs:

image

### PR DESCRIPTION
**Pull request by ahus1**
Closes #189

### CODE REVIEW

**Comment by ahus1** [comment]
@kami619 - this PR pins the versions of the external helm charts, so we shouldn't get unexpected updates any more. I didn't test an upgrade from an earlier version; in the process of upgrading I uninstalled loki and promtail several times using the following comments. I hope that shouldn't be necessary when you test it locally:

```
helm uninstall loki -n monitoring
helm uninstall promtail -n monitoring
task -f loki
task -f promtail
```

Once this is merged, there should be a follow-up issue to configure the retention time for loki; didn't find that in the new chart yet.

**Comment by kami619** [comment]
Even on a plain `task` on a fresh provision of the minikube, I had to jump the hoops to uninstall and reinstall the loki and promtail for the install to be successful, I think its a timing issue more than anything.

```
[promtail] NAME: promtail
[promtail] LAST DEPLOYED: Wed Sep  7 10:05:12 2022
[promtail] NAMESPACE: monitoring
[promtail] STATUS: deployed
[promtail] REVISION: 1
[promtail] TEST SUITE: None
[promtail] NOTES:
[promtail] ***********************************************************************
[promtail]  Welcome to Grafana Promtail
[promtail]  Chart version: 6.3.0
[promtail]  Promtail version: 2.6.1
[promtail] ***********************************************************************
[promtail] 
[promtail] Verify the application is working by running these commands:
[promtail] * kubectl --namespace monitoring port-forward daemonset/promtail 3101
[promtail] * curl http://127.0.0.1:3101/metrics
[loki] Error: Internal error occurred: failed calling webhook "prometheusrulemutate.monitoring.coreos.com": failed to call webhook: Post "https://prometheus-kube-prometheus-operator.monitoring.svc:443/admission-prometheusrules/mutate?timeout=10s": dial tcp 10.105.141.34:443: connect: connection refused
[loki] release "loki" uninstalled
[loki] Release "loki" does not exist. Installing it now.
[loki] Error: Internal error occurred: failed calling webhook "prometheusrulemutate.monitoring.coreos.com": failed to call webhook: Post "https://prometheus-kube-prometheus-operator.monitoring.svc:443/admission-prometheusrules/mutate?timeout=10s": dial tcp 10.105.141.34:443: connect: connection refused
 60  156M   60 94.9M    0     0  1327k      0  0:02:00  0:01:13  0:00:47 3004k
task: Failed to run task "loki": exit status 1

```

**Comment by ahus1** [comment]
Hi @kami619 - you found a concurrency issue: When the Prometheus operator is not running, the installation of recording rules will fail. Thanks for testing this.

I therefore added a change to the `loki.yaml` file that prevents the recording rules to be installed (would only be used as part of the Loki monitoring/alerting). Not it works again even if the Prometheus operator is not (or not yet) running.

Please give it another try. Thanks!

**Review by kami619 — APPROVED** [review]
the changes now look good to me

**Pull request merged**
