### PR TITLE
AWS Global Accelerator Load Balancing

### PR DESCRIPTION
**Pull request by ryanemerson**

### CODE REVIEW

**Comment by ahus1** [comment]
@ryanemerson - thank you for this PR. Great to see this working. 

I have been wondering if  `/health/live` is the right endpoint, and I think it is the right one as it is the only one that will be available even under high load as it is non-blocking. I think it is worth highlighting this in the docs. 

For the probes, it seems they are using HTTP and port 80 at least by looking at the docs and scripts - that surprises me. Could you please double check? It would be good to know where TLS is terminated and possibly re-encrypted in that setup. There shouldn't be unencrypted sections in the setup.

**Comment by ryanemerson** [comment]
> I have been wondering if `/health/live` is the right endpoint, and I think it is the right one as it is the only one that will be available even under high load as it is non-blocking. I think it is worth highlighting this in the docs.

+1 I think it's the best option for now. We created https://github.com/keycloak/keycloak-benchmark/issues/534 to investigate possible improvements and I think this would be a good improvement to focus on after the initial release.


> For the probes, it seems they are using HTTP and port 80 at least by looking at the docs and scripts - that surprises me. Could you please double check? It would be good to know where TLS is terminated and possibly re-encrypted in that setup. There shouldn't be unencrypted sections in the setup.

Great spot @ahus1! The global accelerator actually ignores the health probe settings on the Endpoint group when using ALB/NLB endpoints and delegates to the LB's health checks. In this case we were using the default health check settings which simply opens a TCP connection to the k8s service port. I have updated the docs and scripts so that when we create the k8s Service we explicitly configure the health checks on the NLB.

**Comment by ryanemerson** [comment]
When executing the failover benchmark with the Global Accelerator I'm noticing that we continue to encounter exceptions after the failover to the backup cluster has completed. I need to investigate the root cause before we merge this PR.

Screenshot from 2023-11-14 17-15-59

**Comment by ryanemerson** [comment]
Closing in favour of Route53 based approach: https://github.com/keycloak/keycloak-benchmark/pull/594

**Pull request closed without merging**
