### PR TITLE
Updated ISPN Metrics calculation.

### LINKED ISSUE #636: Horreum: Include latencies from Infinispan Metrics
- Implement logic for retrieving the latencies information from Infinispan metrics.
- Update the schema in Horreum correspondingly.

### PR DESCRIPTION
**Pull request by andyuk1986**
Closes #636

### CODE REVIEW

**Comment by ahus1** [comment]
@andyuk1986 - thank you for this PR. Did you run a test of this in your local repository, and can you please provide a link to the GitHub action run in this issue?

**Comment by andyuk1986** [comment]
@ahus1 yes, I have run it on my fork, here are the list of runs:
https://github.com/andyuk1986/keycloak-benchmark/actions/runs/8920475203 (is latest)
https://github.com/andyuk1986/keycloak-benchmark/actions/runs/8919949259

The numbers are ~the same between runs, so for `memoryUsageTest` is ~23ms, for `cpuUsageForLoginsTest` is ~11ms, for `cpuUsageForCredentialGrantsTest` is between 48-51ms.

**Review by ahus1 — APPROVED** [review]
Thank you for providing the links to the runs, they look good to me.

**Comment by ahus1** [comment]
It is interesting to see that those times are very different. Let's see how they behave on different days of the nightly run, and then see if there is a pattern. It would be good if you could keep that on your radar. Thanks!

**Pull request merged**
