### PR TITLE
Infinispan Operator 2.4.0

### PR DESCRIPTION
**Pull request by ryanemerson**

### CODE REVIEW

**Comment by ahus1** [comment]
@pruivo - could you please review? Looks good to me, still I wonder if I miss something as I am not so familiar with this area. Thanks!

**Comment by ryanemerson** [comment]
Don't merge yet.  2.4.0 has been released to the community-operators, but not community-operators-prod as we're waiting on https://github.com/redhat-openshift-ecosystem/community-operators-prod/pull/4234

I'll add a comment when we're safe to merge.

**Review by pruivo — APPROVED** [review]

**Comment by ahus1** [comment]
@ryanemerson - I assume this is still blocked due to the other PR not being merged yet?

**Comment by ryanemerson** [comment]
Yes. I'm still chasing the maintainers of that repository for clarification on how we can proceed.

**Comment by ryanemerson** [comment]
@ahus1 This is good to merge now.

**Pull request merged**
